// components/Layout/LayoutHeader.tsx
import React from 'react'
import MenuItem from './MenuItem'

const LayoutHeader = () => {
  return (
    <div
      className="bg-header-black fixed top-0 left-0 w-full text-white flex z-50"
      style={{ height: 44, justifyContent: 'center', alignItems: 'center' }}>
      <div className="w-full flex container">
        <MenuItem>UniqueCode</MenuItem>
        <MenuItem>UniqueCode</MenuItem>
        <MenuItem>UniqueCode</MenuItem>
        <MenuItem>UniqueCode</MenuItem>
      </div>
    </div>
  )
}

export default LayoutHeader

// components/LayoutHeader.vue
<template>
  <div class="border-b h-14 fixed top-0 left-0 w-full bg-white">
    <div class="flex px-4 container h-full mx-auto" style="align-items: center">
      <div class="text-xl">UniqueCode</div>
      <div class="flex-grow" />
      RIGHT
    </div>
  </div>
</template>

<script>
export default {}
</script>
