// pages/index.vue
<template>
  <div>
    <client-only>
      <full-page :options="options">
        <div class="section">
          <div class="text-3xl font-bold">UniqueCode</div>
          <div class="text-2xl">세상을 바꾸는 청소년 팀.</div>
          <button
            class="p-2 bg-white hover:bg-black border hover:text-white text-black transition-colors border-black"
          >
            더 알아보기
          </button>
        </div>
        <div class="section">SECTION 2</div>
        <div class="section">SECTION 3</div>
      </full-page>
    </client-only>
  </div>
</template>

<script>
import Vue from 'vue'

export default Vue.extend({
  data: () => ({
    options: {
      licenseKey: '7A6BD9E1-8D334350-80A4BC34-64E1097D',
    },
  }),
})
</script>

// pages/index.tsx
import React, { useEffect } from 'react'
import Layout from '../components/Layout'
import ReactFullpage from '@fullpage/react-fullpage'
import LayoutHeader from '../components/Layout/LayoutHeader'

const Home: React.FC = () => {
  return (
    <Layout noSpacing noHeader>
      <LayoutHeader fullpage />
      <ReactFullpage
        licenseKey="7A6BD9E1-8D334350-80A4BC34-64E1097D"
        anchors={['sec1', 'sec2', 'sec3']}
        render={({ fullpageApi }) => {
          return (
            <div>
              <div className="section">
                <div
                  className="container px-8 flex mx-auto h-full flex-col"
                  style={{
                    justifyContent: 'center',
                    alignItems: 'center',
                  }}>
                  <div className="text-4xl font-bold">UniqueCode</div>
                  <div className="text-xl">세상을 바꾸는 청소년 팀</div>
                  <a className="py-2 px-4 border border-black cursor-pointer transition-colors hover:bg-black hover:text-white">
                    더보기
                  </a>
                </div>
              </div>
              <div className="section">SECTION</div>
              <div className="section">SECTION</div>
            </div>
          )
        }}
      />
    </Layout>
  )
}

export default Home
